name: Deploy to Cloud Run

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  REGISTRY: europe-west3-docker.pkg.dev
  PROJECT_ID: core-nova
  REGION: europe-west3
  SERVICE_NAME: rovet-back-end

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build and publish to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          registry: ${{ env.REGISTRY }}
          project_id: ${{ env.PROJECT_ID }}
          image_name: docker/rovet-back-end
          image_tag: latest,${{ github.sha }}
          dockerfile: ./Dockerfile
          context: .

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/docker/rovet-back-end:latest
          region: ${{ env.REGION }}
          flags: '--allow-unauthenticated --port=8080 --timeout=300 --memory=1Gi'
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            ENVIRONMENT=production
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ACCESS_TOKEN_EXPIRE_MINUTES=31

      - name: Run Database Migrations
        run: |
          # Delete existing job if it exists (ignore errors)
          gcloud run jobs delete migrate-db --region=${{ env.REGION }} --quiet || true
          
          # Create new migration job
          gcloud run jobs create migrate-db \
            --image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/docker/rovet-back-end:latest \
            --command="poetry" \
            --args="run,alembic,upgrade,head" \
            --region=${{ env.REGION }} \
            --set-env-vars="DATABASE_URL=${{ secrets.DATABASE_URL }}" \
            --set-env-vars="ENVIRONMENT=production" \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=3 \
            --parallelism=1
          
          # Execute the migration job
          gcloud run jobs execute migrate-db --region=${{ env.REGION }} --wait 
